import type { CodegenResult, DistilledBinding, DistilledProviderRuntime, Operation } from "./types.ts";

/**
 * Emit the generated capability TypeScript file.
 *
 * Output structure:
 *   - one RpcTarget class per namespace
 *   - one async method per operation, fully typed via the openapi-typescript paths type
 *   - a base WorkerEntrypoint class that exposes namespaces as getters
 *   - a manifest export mapping operationId → request shape
 *
 * Evidence wrapping is generic at the HTTP layer; per-method overrides
 * are layered in by the consumer in a separate non-generated file.
 */

const HEADER = `// AUTO-GENERATED by @capa/codegen — DO NOT EDIT
// Regenerate with: bun run codegen
//
// Source spec: {SPEC_TITLE} v{SPEC_VERSION}
// Operations:  {OP_COUNT}

import { WorkerEntrypoint, RpcTarget } from "cloudflare:workers";
import type { paths } from "./schema.gen.ts";
import { Evidence, type EvidenceBundle, type ProofResult, type CallOptions, {DISTILLED_IMPORT}fetchProof } from "./runtime.ts";
`;

function emitMethod(op: Operation, distilled?: DistilledBinding): string {
	const pathArgs = op.pathParams.map(p => `${toJsName(p)}: string`).join(", ");
	const args = [pathArgs, op.hasBody ? "body?: unknown" : "", "options?: CallOptions"].filter(Boolean).join(", ");

	const pathExpr = op.path.replace(/\{([^}]+)\}/g, (_, p) => "${" + toJsName(p) + "}");
	if (distilled) return emitDistilledMethod(op, distilled, args, pathExpr);

	return `
	/**
	 * ${escapeJsDoc(op.description || op.operationId)}
	 *
	 * \`${op.http.toUpperCase()} ${op.path}\` — risk: ${op.risk}
	 */
	async ${op.method}(${args}): Promise<ProofResult<unknown>> {
		return fetchProof(this.apiKey, {
			operationId: ${JSON.stringify(op.operationId)},
			namespace: ${JSON.stringify(op.namespace)},
			method: ${JSON.stringify(op.method)},
			http: ${JSON.stringify(op.http)},
			path: \`${pathExpr}\`,
			risk: ${JSON.stringify(op.risk)},
			body${op.hasBody ? "" : ": undefined"},
			overrides: this.overrides[${JSON.stringify(op.method)}],
			baseUrl: this.runtimeConfig?.baseUrl,
			extraHeaders: this.runtimeConfig?.extraHeaders,
			prefixOverride: this.runtimeConfig?.prefixOverride,
			options,
		});
	}`;
}

function emitDistilledMethod(op: Operation, distilled: DistilledBinding, args: string, pathExpr: string): string {
	const operation = distilled.operationDynamicImport
		? `loadDistilled(${JSON.stringify(distilled.operationDynamicImport)}, ${JSON.stringify(distilled.operationExport)})`
		: distilled.operationExport;
	const inputParts = [
		...op.pathParams.map(param => `${JSON.stringify(param)}: ${toJsName(param)}`),
		...(op.hasBody ? ["...(body as Record<string, unknown> || {})"] : []),
	];
	const input = `{ ${inputParts.join(", ")} } as ${distilled.inputType}`;
	return `
	/**
	 * ${escapeJsDoc(op.description || op.operationId)}
	 *
	 * \`${op.http.toUpperCase()} ${op.path}\` — risk: ${op.risk}
	 */
	async ${op.method}(${args}): Promise<ProofResult<${distilled.outputType}>> {
		const input = ${input};
		return distilledProof({
			operationId: ${JSON.stringify(op.operationId)},
			namespace: ${JSON.stringify(op.namespace)},
			method: ${JSON.stringify(op.method)},
			http: ${JSON.stringify(op.http)},
			path: \`${pathExpr}\`,
			risk: ${JSON.stringify(op.risk)},
			body${op.hasBody ? "" : ": undefined"},
			input,
			operation: async operationInput => runDistilled(await ${operation}, operationInput, this.apiKey, options, this.runtimeConfig),
			overrides: this.overrides[${JSON.stringify(op.method)}],
			baseUrl: this.runtimeConfig?.baseUrl,
			extraHeaders: this.runtimeConfig?.extraHeaders,
			prefixOverride: this.runtimeConfig?.prefixOverride,
			options,
		});
	}`;
}

function emitNamespaceClass(namespace: string, ops: Operation[], distilledBindings: Map<string, DistilledBinding>): string {
	const className = toPascalCase(namespace) + "Resource";

	return `
export class ${className} extends RpcTarget {
	constructor(
		private apiKey: string | undefined,
		private overrides: Record<string, import("./runtime.ts").MethodOverride> = {},
		private runtimeConfig?: import("./runtime.ts").RuntimeConfig,
	) {
		super();
	}
${ops.map(op => emitMethod(op, distilledBindings.get(op.operationId))).join("\n")}
}`;
}

function emitDistilledRuntime(bindings: Map<string, DistilledBinding>, provider: DistilledProviderRuntime): string {
	const imports = new Map<string, Set<string>>();
	for (const binding of bindings.values()) {
		const exports = imports.get(binding.operationImport) || new Set<string>();
		if (!binding.operationDynamicImport) exports.add(binding.operationExport);
		exports.add(`type ${binding.inputType}`);
		exports.add(`type ${binding.outputType}`);
		imports.set(binding.operationImport, exports);
	}
	const operationImports = Array.from(imports.entries())
		.map(([from, names]) => `import { ${Array.from(names).join(", ")} } from ${JSON.stringify(from)};`)
		.join("\n");
	return `${operationImports}
import * as Effect from "effect/Effect";
import * as Layer from "effect/Layer";
import * as Redacted from "effect/Redacted";
import * as FetchHttpClient from "effect/unstable/http/FetchHttpClient";
import { Credentials } from ${JSON.stringify(provider.credentialsImport)};

async function loadDistilled<Input, Output>(modulePath: string, exportName: string): Promise<(input: Input) => Effect.Effect<Output, unknown, unknown>> {
\tconst module = await import(modulePath) as Record<string, unknown>;
\treturn module[exportName] as (input: Input) => Effect.Effect<Output, unknown, unknown>;
}

function distilledLayer(apiKey: string, runtimeConfig?: import("./runtime.ts").RuntimeConfig) {
\treturn Layer.mergeAll(
\t\tFetchHttpClient.layer,
\t\tLayer.succeed(Credentials, { ${provider.secretField}: Redacted.make(apiKey), apiBaseUrl: runtimeConfig?.baseUrl || ${JSON.stringify(provider.defaultBaseUrl)} }),
\t);
}

async function runDistilled<Input, Output>(
\toperation: (input: Input) => Effect.Effect<Output, unknown, unknown>,
\tinput: Input,
\tapiKey: string | undefined,
\toptions?: CallOptions,
\truntimeConfig?: import("./runtime.ts").RuntimeConfig,
): Promise<Output> {
\tconst effectiveApiKey = options?.auth?.apiKey ?? apiKey;
\tif (!effectiveApiKey) throw new Error("set the capability API key secret or pass options.auth.apiKey");
\tconst effect = operation(input).pipe(Effect.provide(distilledLayer(effectiveApiKey, runtimeConfig))) as Effect.Effect<Output, unknown, never>;
\treturn Effect.runPromise(effect);
}`;
}

function emitWorkerEntrypoint(
	namespaces: Record<string, Operation[]>,
	capabilityName: string,
): string {
	const apiKeyBinding = `${toEnvName(capabilityName)}_API_KEY`;
	const getterDecls = Object.keys(namespaces).map(ns => {
		const className = toPascalCase(ns) + "Resource";
		const safeNs = toJsName(ns);
		return `\tget ${safeNs}(): ${className} {\n\t\treturn new ${className}(this.env.${apiKeyBinding}, this.overrides[${JSON.stringify(ns)}] || {}, this.runtimeConfig);\n\t}`;
	});

	return `\ninterface Env {\n\t${apiKeyBinding}?: string;\n}\n\nexport class ${toPascalCase(capabilityName)}Capability extends WorkerEntrypoint<Env> {\n\tprotected overrides: Record<string, Record<string, import("./runtime.ts").MethodOverride>> = {};\n\tprotected runtimeConfig?: import("./runtime.ts").RuntimeConfig;\n\n${getterDecls.join("\n\n")}\n}`;
}

function emitManifest(namespaces: Record<string, Operation[]>): string {
	const entries: string[] = [];
	for (const ops of Object.values(namespaces)) {
		for (const op of ops) {
			entries.push(`	${JSON.stringify(op.operationId)}: ${JSON.stringify({
				namespace: op.namespace,
				method: op.method,
				http: op.http,
				path: op.path,
				risk: op.risk,
			})}`);
		}
	}
	return `
export const manifest = {
${entries.join(",\n")}
} as const;

export type OperationId = keyof typeof manifest;
`;
}

export function emit(
	codegen: CodegenResult,
	capabilityName: string,
	distilledBindings: Map<string, DistilledBinding> = new Map(),
	distilledProvider?: DistilledProviderRuntime,
): { capability: string; manifest: string } {
	const header = HEADER
		.replace("{SPEC_TITLE}", codegen.specTitle)
		.replace("{SPEC_VERSION}", codegen.specVersion)
		.replace("{OP_COUNT}", String(codegen.operationCount))
		.replace("{DISTILLED_IMPORT}", distilledBindings.size > 0 ? "distilledProof, " : "");

	const distilledRuntime = distilledProvider && distilledBindings.size > 0
		? emitDistilledRuntime(distilledBindings, distilledProvider)
		: "";
	const namespaceClasses = Object.entries(codegen.namespaces)
		.map(([ns, ops]) => emitNamespaceClass(ns, ops, distilledBindings))
		.join("\n");

	const entrypoint = emitWorkerEntrypoint(codegen.namespaces, capabilityName);
	const manifestSrc = emitManifest(codegen.namespaces);
	const manifestHeader = header.replace("distilledProof, ", "");

	const capability = [header, distilledRuntime, namespaceClasses, entrypoint].filter(Boolean).join("\n");

	return { capability, manifest: manifestHeader + manifestSrc };
}

// ─── helpers ──────────────────────────────────────────────────────

const RESERVED = new Set([
	"break", "case", "catch", "class", "const", "continue", "debugger",
	"default", "delete", "do", "else", "enum", "export", "extends", "false",
	"finally", "for", "function", "if", "import", "in", "instanceof", "new",
	"null", "return", "super", "switch", "this", "throw", "true", "try",
	"typeof", "var", "void", "while", "with", "yield",
]);

function toJsName(s: string): string {
	const camelCased = s
		.replace(/[^a-zA-Z0-9]+(.)/g, (_, c) => c.toUpperCase())
		.replace(/^[^a-zA-Z0-9]+/, "")
		.replace(/[^a-zA-Z0-9]+/g, "");
	return RESERVED.has(camelCased) ? camelCased + "_" : camelCased;
}

function toPascalCase(s: string): string {
	const camel = toJsName(s);
	return camel.charAt(0).toUpperCase() + camel.slice(1);
}

function toEnvName(s: string): string {
	return s.replace(/[^a-zA-Z0-9]+/g, "_").toUpperCase();
}

function escapeJsDoc(s: string): string {
	return s.replace(/\*\//g, "*\\/").slice(0, 200);
}
