import type { CodegenResult, Operation, ResourceBackend } from "./types.ts";

/**
 * Emit the generated capability TypeScript file.
 *
 * Output structure:
 *   - one RpcTarget class per namespace
 *   - one async method per operation, fully typed via the openapi-typescript paths type
 *   - a base WorkerEntrypoint class that exposes namespaces as getters
 *   - a manifest export mapping operationId → request shape
 *
 * Evidence wrapping is generic at the HTTP layer; per-method overrides
 * are layered in by the consumer in a separate non-generated file.
 */

const HEADER = `// AUTO-GENERATED by @capa/codegen — DO NOT EDIT
// Regenerate with: bun run codegen
//
// Source spec: {SPEC_TITLE} v{SPEC_VERSION}
// Operations:  {OP_COUNT}

import { WorkerEntrypoint, RpcTarget } from "cloudflare:workers";
import type { paths } from "./schema.gen.ts";
import { Evidence, type EvidenceBundle, type ProofResult, type CallOptions, fetchProof } from "./runtime.ts";
`;

function emitMethod(op: Operation): string {
	const pathArgs = op.pathParams.map(p => `${toJsName(p)}: string`).join(", ");
	const args = [pathArgs, op.hasBody ? "body?: unknown" : "", "options?: CallOptions"].filter(Boolean).join(", ");

	const pathExpr = op.path.replace(/\{([^}]+)\}/g, (_, p) => "${" + toJsName(p) + "}");

	return `
	/**
	 * ${escapeJsDoc(op.description || op.operationId)}
	 *
	 * \`${op.http.toUpperCase()} ${op.path}\` — risk: ${op.risk}
	 */
	async ${op.method}(${args}): Promise<ProofResult<unknown>> {
		return fetchProof(this.apiKey, {
			operationId: ${JSON.stringify(op.operationId)},
			namespace: ${JSON.stringify(op.namespace)},
			method: ${JSON.stringify(op.method)},
			http: ${JSON.stringify(op.http)},
			path: \`${pathExpr}\`,
			risk: ${JSON.stringify(op.risk)},
			body${op.hasBody ? "" : ": undefined"},
			overrides: this.overrides[${JSON.stringify(op.method)}],
			baseUrl: this.runtimeConfig?.baseUrl,
			extraHeaders: this.runtimeConfig?.extraHeaders,
			prefixOverride: this.runtimeConfig?.prefixOverride,
			options,
		});
	}`;
}

function emitNamespaceClass(namespace: string, ops: Operation[]): string {
	const className = toPascalCase(namespace) + "Resource";

	return `
export class ${className} extends RpcTarget {
	constructor(
		private apiKey: string | undefined,
		private overrides: Record<string, import("./runtime.ts").MethodOverride> = {},
		private runtimeConfig?: import("./runtime.ts").RuntimeConfig,
	) {
		super();
	}
${ops.map(emitMethod).join("\n")}
}`;
}

function emitWorkerEntrypoint(
	namespaces: Record<string, Operation[]>,
	capabilityName: string,
	resourceBackends: ResourceBackend[],
): string {
	const apiKeyBinding = `${toEnvName(capabilityName)}_API_KEY`;
	const backendByNamespace = new Map(resourceBackends.map(backend => [backend.namespace, backend]));
	const getterDecls = Object.keys(namespaces).map(ns => {
		const className = backendByNamespace.get(ns)?.className || toPascalCase(ns) + "Resource";
		const safeNs = toJsName(ns);
		return `\tget ${safeNs}(): ${className} {\n\t\treturn new ${className}(this.env.${apiKeyBinding}, this.overrides[${JSON.stringify(ns)}] || {}, this.runtimeConfig);\n\t}`;
	});

	return `\ninterface Env {\n\t${apiKeyBinding}?: string;\n}\n\nexport class ${toPascalCase(capabilityName)}Capability extends WorkerEntrypoint<Env> {\n\tprotected overrides: Record<string, Record<string, import("./runtime.ts").MethodOverride>> = {};\n\tprotected runtimeConfig?: import("./runtime.ts").RuntimeConfig;\n\n${getterDecls.join("\n\n")}\n}`;
}

function emitManifest(namespaces: Record<string, Operation[]>): string {
	const entries: string[] = [];
	for (const ops of Object.values(namespaces)) {
		for (const op of ops) {
			entries.push(`	${JSON.stringify(op.operationId)}: ${JSON.stringify({
				namespace: op.namespace,
				method: op.method,
				http: op.http,
				path: op.path,
				risk: op.risk,
			})}`);
		}
	}
	return `
export const manifest = {
${entries.join(",\n")}
} as const;

export type OperationId = keyof typeof manifest;
`;
}

export function emit(
	codegen: CodegenResult,
	capabilityName: string,
	resourceBackends: ResourceBackend[] = [],
): { capability: string; manifest: string } {
	const header = HEADER
		.replace("{SPEC_TITLE}", codegen.specTitle)
		.replace("{SPEC_VERSION}", codegen.specVersion)
		.replace("{OP_COUNT}", String(codegen.operationCount));
	const backendImports = resourceBackends
		.map(backend => `import { ${backend.className} } from ${JSON.stringify(backend.importPath)};`)
		.join("\n");

	const namespaceClasses = Object.entries(codegen.namespaces)
		.map(([ns, ops]) => emitNamespaceClass(ns, ops))
		.join("\n");

	const entrypoint = emitWorkerEntrypoint(codegen.namespaces, capabilityName, resourceBackends);
	const manifestSrc = emitManifest(codegen.namespaces);

	const capability = [header, backendImports, namespaceClasses, entrypoint].filter(Boolean).join("\n");

	return { capability, manifest: header + manifestSrc };
}

// ─── helpers ──────────────────────────────────────────────────────

const RESERVED = new Set([
	"break", "case", "catch", "class", "const", "continue", "debugger",
	"default", "delete", "do", "else", "enum", "export", "extends", "false",
	"finally", "for", "function", "if", "import", "in", "instanceof", "new",
	"null", "return", "super", "switch", "this", "throw", "true", "try",
	"typeof", "var", "void", "while", "with", "yield",
]);

function toJsName(s: string): string {
	const camelCased = s
		.replace(/[^a-zA-Z0-9]+(.)/g, (_, c) => c.toUpperCase())
		.replace(/^[^a-zA-Z0-9]+/, "")
		.replace(/[^a-zA-Z0-9]+/g, "");
	return RESERVED.has(camelCased) ? camelCased + "_" : camelCased;
}

function toPascalCase(s: string): string {
	const camel = toJsName(s);
	return camel.charAt(0).toUpperCase() + camel.slice(1);
}

function toEnvName(s: string): string {
	return s.replace(/[^a-zA-Z0-9]+/g, "_").toUpperCase();
}

function escapeJsDoc(s: string): string {
	return s.replace(/\*\//g, "*\\/").slice(0, 200);
}
